name: Stream URL Fetcher

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  fetch_stream_url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install selenium undetected-chromedriver

    - name: Download ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run Python Script
      run: python fetch_stream.py
