name: Stream URL Fetcher

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  fetch_stream_url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Updated to v3 to avoid Node 12 warnings

    - name: Set up Python environment
      uses: actions/setup-python@v4  # Updated to v4 to avoid Node 12 warnings
      with:
        python-version: '3.8'

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        if [ ! -f /usr/bin/chromedriver ]; then
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        else
          echo "Chromedriver already exists, skipping symlink creation."
        fi

    - name: Install Selenium
      run: pip install selenium

    - name: Run Python Script
      env:
        PATH: /usr/lib/chromium-browser/:$PATH  # Ensure Chromedriver is in PATH
      run: python fetch_stream.py
