name: Fetch Stream URL

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  push:
    branches:
      - main  # Triggers on push to main

jobs:
  fetch_m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Update to at least version 16

      - name: Install dependencies
        run: |
          npm install puppeteer

      - name: Run M3U8 fetch script
        run: node fetch_m3u8.js
