name: Fetch Stream URL

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  push:
    branches:
      - main  # Triggers on push to main

jobs:
  fetch_m3u8_url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo cp /usr/bin/chromedriver /usr/bin/chromedriver

      - name: Run fetch_stream.py
        run: |
          python fetch_stream.py
