name: Fetch Stream URL

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  push:
    branches:
      - main  # Triggers on push to main
      
jobs:
  fetch-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust the version as needed

      - name: Install dependencies
        run: |
          pip install selenium
          apt-get update
          apt-get install -y chromium-chromedriver
          cp /usr/bin/chromedriver /usr/bin/chromedriver

      - name: Run fetch_stream.py
        run: python fetch_stream.py
